### ISSUE TITLE
[BUG] Unclear that anything is happening in the UI when docker images are building

### ISSUE THREAD

**Issue by BenElgar** [deref/exo#105]
**Describe the bug**
The UI doesn't show any processes or inform you that anything is happening when a docker image is building. 

**To Reproduce**
1. Run `exo run docker-compose.yaml` for a docker compose file for which you don't have any cached docker images
2. Observe in the UI that the workspace is created with no components

**Expected behavior**
A loading bar or spinner should be displayed

**Comment by brandonbloom** [comment]
self-assigning b/c this is my top priority, i'm making really good progress on it.

**Comment by brandonbloom** [comment]
@BenElgar as a workaround while debugging other docker stuff, see `NOTE: [DOCKER_PROGRESS]`. The output gets written to stdout, which isn't part of the normal logs. You can do `tail -F ~/.exo/var/exod.stdout` (or `.dev/var/exod.stdout`)
