### ISSUE TITLE
[BUG] Logs are truncated

### ISSUE THREAD

**Issue by BenElgar** [deref/exo#126]
**Describe the bug**
Long log lines are truncated and/or split across lines.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a docker-compose.yaml like so:
```docker-compose
services:
  web:
    image: bash
    command: "printf '.%.0s' {1..9000}"
```
2. Run it with `exo run docker-compose.yaml`

**Expected behaviour**
One log line printed with 9000 dots on one line in both the UI and the CLI. Instead what happens is that some smaller number of dots is printed in the UI (this seems to be consistently 8080) and none are printed in the CLI.

If the 9000 is increased to a much larger number the dots appear to get split across multiple lines in the UI but still don't sum to the correct number.

**Comment by BenElgar** [comment]
Fwiw I ran into this bug when trying to log the output of docker commands and found that the logs were being truncated at 1024 characters.

**Comment by kendru** [comment]
Yeah, I think that truncating long log lines (at least at 1024 characters) is not the write behaviour. I'll set a very large limit so that we should never run into it with typical logs.
