### ISSUE TITLE
[BUG] Fonts not bundled with release

### ISSUE THREAD

**Issue by brandonbloom** [deref/exo#145]
We're using fonts that are not bundled with the release, so if the user doesn't have them installed, they don't work!

**Comment by brandonbloom** [comment]
So I was about to take this off your plate & went looking to see what font we're using. Looks like Fira Code, but that's one of those weird fonts with fancy ligatures. I think folks have pretty strong preferences both in favor and against these ligatures. I don't think we should use Fira Code by default because of this.

@jwmza Can you pick a different font please? My advice would be to select one from https://fonts.google.com/ (double check, but they should all have the Open Font License).

**Comment by jwmza** [comment]
@brandonbloom there's a CSS toggle for ligatures on/off - Fira Code is a really good code font, license here: https://github.com/tonsky/FiraCode/blob/master/LICENSE

I think we should use Fira Code and default ligatures off with an optional switch potentially added later. Is there a reason other than ligatures you'd be against it?

**Comment by brandonbloom** [comment]
My main issue was the ligatures. I wasn't aware of the toggle. Thanks for pointing that out.

We can use this font, but according to the license we must provide notice:

```
2) Original or Modified Versions of the Font Software may be bundled,
redistributed and/or sold with any software, provided that each copy
contains the above copyright notice and this license. These can be
included either as stand-alone text files, human-readable headers or
in the appropriate machine-readable metadata fields within text or
binary files as long as those fields can be easily viewed by the user.
```

We'd have to put a license in to a `NOTICE.md` file in the root of the repository, as well as provide some way to access it in the GUI as well. For example, see `chrome://terms/`or `about:license` in Firefox.

**Comment by jwmza** [comment]
Sounds good, I'll get these bundled.

Presumably we are all good with "Inter" as the sans serif font of choice @brandonbloom ?
https://rsms.me/inter/ https://github.com/rsms/inter/blob/master/LICENSE.txt

**Comment by brandonbloom** [comment]
That's fine too. It also requires a NOTICE entry.
