### ISSUE TITLE
[BUG] Log viewer is scrolling, should be wrapping

### ISSUE THREAD

**Issue by brandonbloom** [deref/exo#151]
![image](https://user-images.githubusercontent.com/119164/129090433-4b15fd0c-dc5e-4b6e-8169-d0cf55feebc3.png)
![image](https://user-images.githubusercontent.com/119164/129090453-2a760fd2-e749-4959-b1bb-ed6d429f3235.png)

**Comment by jwmza** [comment]
Fixed #161
