### ISSUE TITLE
[BUG] Log prefix contrast too low

### ISSUE THREAD

**Issue by BenElgar** [deref/exo#158]
![image](https://user-images.githubusercontent.com/3443024/129057514-822df72a-997b-4bd8-95b0-0683b51723b6.png)

Contrast of the prefix of the output of tailing logs is so low as to be illegible in dark terminals.

**Comment by brandonbloom** [comment]
I'm not sure what to do about this unless we can somehow detect either the terminal theme or the OS light/dark mode setting (or both?)

Suggestions?

**Comment by BenElgar** [comment]
I'm not entirely sure what the best option is. I've tried to find a way of getting the background colour but none of the solutions I immediately found seemed to work (or I was using them wrong). But apps like `htop` and `nmtui` manage it so it must be possible.

A simpler solution would probably just be to pick colours that work well on both dark and light terminals. If we stay away from very light or dark colours we can probably do a good enough job that we don't have to think about it.

**Comment by brandonbloom** [comment]
OK, let's see if we can fix this issue by improving the color pallet algorithm. It's here: https://github.com/deref/exo/blob/ff8800377a2cc1613924e156d05b39ee3afa22f7/cmd/exo/logs.go#L153-L162

Maybe @jwmza has some ideas for that?

Separately, we should probably figure out reliable terminal color detection, especially if we do a proper interactive TUI for the log viewer at some point.

**Comment by jwmza** [comment]
There are two separate options:

If it is possible to detect or select dark/light mode, we can get the best possible color generation with the following:

- Select dark, high saturation colors for a light background
- Select bright, low saturation colors for a dark background
- Brighten colors around ~blue/indigo and darken colors around ~yellow with a 360-degree-(hue)-wide sine wave.

If it is not possible to detect dark/light mode, the colors will need to be much more muddy/grey in order to look good on both, and will need to be ~40-60% brightness to the human eye

**Comment by jwmza** [comment]
> A simpler solution would probably just be to pick colours that work well on both dark and light terminals. If we stay away from very light or dark colours we can probably do a good enough job that we don't have to think about it.

Unfortunately, there is no way to do this without picking overall quite bad colors.

It will always be much nicer to have brighter, less saturated colors on a dark bg (so bright and so desaturated that they would look awful on a light bg) and dark, more saturated colors on light bg (so dark and so saturated that they would look awful on a dark bg)

**Comment by jwmza** [comment]
For now a decent middleground might be
```
 		r, g, b := rgbterm.HSLtoRGB(h, 2/3, 2/3) 
```

**Comment by brandonbloom** [comment]
OK, going to assign to @BenElgar to figure out how we determine light/dark terminal background in a reasonably cross-platform way.

After that, if necessary, can reassign to @jwmza to figure out color pallets that work. If the light/dark background detection is unreliable, then we fallback to an ugly pallet.
