### ISSUE TITLE
[BUG] Race condition in `DescribeProcesses`

### ISSUE THREAD

**Issue by brandonbloom** [deref/exo#205]
**Describe the bug**

The describe process internals calls out to `ps` and other system utilities, so there is a race where the process may have died in between checking if it is running and then calling MemoryInfo, Connections, etc on that process.

**To Reproduce**

1. go build ./cmd/tick
2. cd `./examples/voluminous-logs`
3. `exo run`
4. Open the GUI
5. in another terminal, `exo stop`
6. watch the gui & you'll likely see an error popup! if not, try `exo start` and `exo stop` again.
7. inspect the `~/.exo/var/exod.log` to see it's something like `exit status 1`

**Expected behavior**

The error handling in `DescribeProcesses` should be much more robust.

**Comment by brandonbloom** [comment]
@BenElgar Did you write this code? Would you mind taking a look at what we can do about this?

**Comment by brandonbloom** [comment]
Ideally, all of the logic that is in this `DescribeProcesses` stuff should move in to the `refresh` method in processes, so that we can have one uniform handling for how frequently we refresh to read state from external resources.

**Comment by BenElgar** [comment]
Ah yes, I pushed a simple fix earlier.

**Comment by brandonbloom** [comment]
So I think that you can more generally detect `errdefs.Conflict` for that specific "restarting" problem:

- https://github.com/deref/exo/pull/221/files#diff-4e94592898bb77a7e2145c8520529955d484ea3015c3e2159b52d4b22e2d9584R74
- https://github.com/moby/moby/blob/ba2adeebdb8d4ec442f1d3107405ae55d0c1a0c2/errdefs/defs.go#L13-L17

However, this is a more general problem. The issue I ran in to above affects unix processes too, not just docker containers.

**Comment by BenElgar** [comment]
This should have been fixed by https://github.com/deref/exo/pull/256.
