### ISSUE TITLE
[BUG] `exo ls` and `exo ps` output not sorted

### ISSUE THREAD

**Issue by brandonbloom** [deref/exo#206]
```
$ exo ls
eight   2139wqc65f96v4g8pwgr414bgm   process
five    9x3h1hg7ggjyns43ym2hzrtk80   process
four    y1526vhtfmh8w63fxwp87y0zp0   process
nine    hy3p3mbyw8b6rz04eab0kdkw78   process
one     n6cp9rrbgcd0p0n91zg7nzrebm   process
seven   njvask0rqaz0pcgy632mxp5934   process
size    vg77ad5hazfqs9vp67qhgcbg88   process
ten     494gpa8df0x9xqyqmdxq5ps2hg   process
three   yw7szzfa0wrr4ktatb90j2afk4   process
two     07g95x3gxms5ghnz0b0x71sqb4   process
```

**Comment by brandonbloom** [comment]
There are other things that are not sorted, like job reporting and the like. Maybe if the output of `describe-components` is sorted, that would help.

**Comment by BenElgar** [comment]
They seem sorted to me, alphanumerically by name. They also appear to be consistent between `exo ls` and `exo ps`. In what other order would we like them sorted?

**Comment by brandonbloom** [comment]
heh, my bad, clear brain fart when i expected that to be one, two, three, etc - sorted by the order in the procfile or something. obviously nonsensical. apologies for the noise
