### ISSUE TITLE
[BUG] process list UX still confusing

### ISSUE THREAD

**Issue by brandonbloom** [deref/exo#208]
![image](https://user-images.githubusercontent.com/119164/129799930-b97a796b-0dcb-47ab-89b6-dfab2ada2b34.png)

**Comment by brandonbloom** [comment]
From a user in dark mode:

> One small confusion with the UI is the "Stop process" button, instead of a grey square maybe change it to red or something since the grey one looks like I'm selecting the process.

**Comment by jwmza** [comment]
Is this complete with the new start/stop icons?

![image](https://user-images.githubusercontent.com/51100181/132732637-7795aa67-d138-4b4d-9748-1766393c7095.png)
![image](https://user-images.githubusercontent.com/51100181/132732660-5dc11fc4-9624-4532-b26e-195ab3de5ec9.png)

**Comment by jwmza** [comment]
Should be noted that this UI will materially change when we remake this list as a cards list.

I also still think the running/not running indicator is not ideal, plus we need some sort of broken/errored icon for components that are incorrectly configured or can't run.

**Comment by jwmza** [comment]
Okay I think this "bug" is fixed now - there will always be improvements to be made in future, but the new cards list is good in my books. Feel free to re-open or make a new issue regarding a particular problem with it if you disagree :)
