### ISSUE TITLE
[BUG] docker-compose and exo run build different images

### ISSUE THREAD

**Issue by BenElgar** [deref/exo#223]
For non-trivial builds (e.g. awesome-compose/sparkjava) `exo run` and `docker-compose up` build different images. This would appear to be because we provide a different build context to docker. We don't take the `.dockerignore` file into account which would certainly explain it but that isn't sufficient explanation since it appears to happen for images where there is no dockerignore file.

**Comment by brandonbloom** [comment]
Is there a separate issue for "implement .dockerignore"? Can use this ticket for that, but then follow-up to figure out the other differences.

**Comment by BenElgar** [comment]
I created one here: https://github.com/deref/exo/issues/224

**Comment by brandonbloom** [comment]
@BenElgar how far off are we on this one now?

**Comment by BenElgar** [comment]
If I've done it right, this should be fixed in https://github.com/deref/exo/pull/297.

**Comment by BenElgar** [comment]
Ah, no, I've managed to find cases where the images still aren't the same. This would appear to be because the selection of cache-eligible images is different, though right now I'm not clear on why.

Since, with #297, the build context appears to be the same I think that this is substantially less pressing than previously.
