### ISSUE TITLE
[FEATURE] Ability to rename workspaces

### ISSUE THREAD

**Issue by peyloride** [deref/exo#231]
**Is your feature request related to a problem? Please describe.**
In the GUI it's not clear to which workspace is what. For example in my project there are 3 backend micro service talking to each other and I want to see which is what but I can't.
![image](https://user-images.githubusercontent.com/10589068/130045303-f00977a9-df71-4bee-8ded-b191a6b994f9.png)
 

**Describe the solution you'd like**
These are the ID's of workspaces I guess, maybe someone can add name field and make it editable (if its default comes from project folder, that would be great)

**Comment by jwmza** [comment]
@peyloride thanks for the request, I agree we should have renamable workspaces.

In the meantime I'm going to refactor the workspace list layout to prioritize the project directory, so that you can see the end and not just the start of those.

**Comment by brandonbloom** [comment]
Thanks @peyloride, looks like @jwmza has a pretty good fix for the problem of being unable to tell workspaces apart over in #234. That will go out in our next release sometime next week.

In the meantime, you can use `exo workspace ls` in your terminal to see the full names clearly.

Going forward, we'll probably introduce a notion of "project", for which there may be many workspaces. I suspect that workspaces will remain anonymous and identified primarily by directory, but projects, stacks, etc may all become named. Still a fair amount of design work and TBD elements there. Tracking over here: https://github.com/deref/exo/issues/183

**Comment by peyloride** [comment]
Thanks everyone, these are awesome news.

**Comment by jwmza** [comment]
In light of @brandonbloom 's notice above re: #183 and the fix for readability in #234, I'll close this issue now.

However it is probably a good idea to soon use the shortest unique workspace directory label instead of the entire directory from root in most UI elements where the directory is displayed, in order to reduce visual noise.
