### ISSUE TITLE
[BUG] Improper rendering of control codes in GUI

### ISSUE THREAD

**Issue by jwmza** [deref/exo#232]
**Describe the bug**
I tried to add the `cal` program as a process and it seems like the special formatting for the highlighted text at the current date is not rendering properly, despite that we've recently added color/highlight/formatting in the GUI logs. @brandonbloom 

**To Reproduce**
1. Add `cd / && cal` as a process
2. Run the process
4. See error in **Logs** panel

**Expected behavior**
See expected screenshot below.

**Screenshots**
Bug in **exo** GUI:
![image](https://user-images.githubusercontent.com/51100181/130078746-ddb407b1-8ee7-4188-969e-746f952ee034.png)

Expected:
![image](https://user-images.githubusercontent.com/51100181/130078965-3d6e898c-7345-41f3-97e6-c419a661a361.png)

**System Info (please complete the following information):**
 - OS: Ubuntu 20.04 LTS in Windows WSL2
 - Component: GUI
 - Version: Dev (>2021.08.17)

**Comment by BenElgar** [comment]
Can reproduce with a Procfile that looks like this:
```
p: cal --color=always
```

This results in this incorrect output in the GUI:
![image](https://user-images.githubusercontent.com/3443024/131697747-4272388b-d409-47bc-aa8e-772218868bdf.png)

and this (correct) output in the terminal:
![image](https://user-images.githubusercontent.com/3443024/131697940-f4e1b77f-63bd-4d91-9626-34e0cd5b232a.png)
