### ISSUE TITLE
[BUG] Multiline instant processes don't render all logs on run

### ISSUE THREAD

**Issue by jwmza** [deref/exo#233]
**Describe the bug**
When running `cal`, which is supposed to immediately show a multi-line human readable text output of the current calendar month and weekday, the GUI seems to randomly show anywhere from 1 to 8 lines in the logs instead of the exact amount the command would regularly show in a terminal. Sometimes it only prints one or two lines, sometimes many. Can't sense any pattern to why there's a different amount each time.

**To Reproduce**
1. Add `cd / && cal` as a process
2. Run the process
4. See error in **Logs** panel

**Screenshots**
![image](https://user-images.githubusercontent.com/51100181/130080336-a326a2ba-e952-4eb6-ad0d-4cb3c6a60aa6.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/51100181/130080435-7b34ae41-b46a-45a0-a763-eb4015f9d85c.png)

**System Info (please complete the following information):**
 - OS: Ubuntu 20.04 LTS in Windows WSL2
 - Component: GUI
 - Version: Dev (>2021.08.17)

**Comment by BenElgar** [comment]
I can confirm I can reproduce this. It appears to be solved by doing `cal && sleep 1` which I assume means that the issue is that the log collector is stopping too soon.

**Comment by jwmza** [comment]
Would it be reasonable to pad the log collector's lifetime by a second or so in order to fix this for all similar cases @BenElgar ?

I'm assuming the issue here is a race condition where the emission of many "instant" logs and the stopping of the log collector are all scheduled for the same moment in time.

**Comment by BenElgar** [comment]
I believe I've fixed this in the linked PR.
