### ISSUE TITLE
[FEATURE] environment variables CLI/GUI

### ISSUE THREAD

**Issue by brandonbloom** [deref/exo#272]
**Is your feature request related to a problem? Please describe.**

I want to see what the effective environment variables are in my workspace. In the future, I'd like to also be able to add/remove/edit variables too.

**Describe the solution you'd like**

Command to print the current workspace environment as a .env file:

```
exo env
```

And a "Variables" page somewhere in the GUI showing the same information.

**Comment by BenElgar** [comment]
Just to be clear, is this just the values in the `.env` file merged with your shell environment?

**Comment by brandonbloom** [comment]
It's whatever the "WorkspaceEnvironment" gets set to that components can use. Right now, yeah, I think that is just the launched env plus the .env file.

**Comment by BenElgar** [comment]
:+1:

**Comment by brandonbloom** [comment]
CLI is in #284, but could still use a GUI.
