### ISSUE TITLE
[BUG] exo fails to parse unquoted integers from docker compose files

### ISSUE THREAD

**Issue by catleeball** [deref/exo#286]
**Describe the bug**

When running `exo run` or `exo apply` on a docker-compose.yml file containing environment variables whose values aren't explicitly quoted strings, it throws an error:

```
Error: applying manifest: parsing: expected values to be string, got 1
applying manifest: parsing: expected values to be string, got 1
```

Here are two compose files where this issue was encountered:

- https://gist.github.com/catleeball/5ff10090b22b32b22e0d3d7ed3674d2d
- https://github.com/restic/rest-server/blob/master/examples/compose-with-grafana/docker-compose.yml

This is similar to https://github.com/deref/exo/issues/279, figured I'd open this in a separate bug in case it's helpful for tracking.

-----

**To Reproduce**
1. Have a docker-compose.yml file
2. Set an environment variable a value such as `1` without quotes
3. Run `exo run` or `exo apply`

-----

**Expected behavior**

Exo runs the docker-compose.yml file as docker-compose would, having parsed the integer as a string despite not having quotes.

-----

**System Info (please complete the following information):**
 - OS: Ubuntu 21.04 (linux 5.11)
 - Component: cli
 - Version: 2021.08.31

-----

**Additional context**

Thanks for your hard work on Exo!

**Comment by BenElgar** [comment]
Thank you very much for the reports! There are open PRs for each of them now, which we'll try and merge soon. :)
