### ISSUE TITLE
[FEATURE] Support compose network_mode?

### ISSUE THREAD

**Issue by mausch** [deref/exo#300]
<pre>
exo run --format compose <a href="https://github.com/SolrNet/SolrNet/blob/65d74d66273be7dd993154399798b75d3e856b62/cloud-tests-compose.yml">cloud-tests-compose.yml</a>
</pre>

fails with 'unknown field "network_mode"'

**Comment by brandonbloom** [comment]
This should be fixed by https://github.com/deref/exo/pull/283

We'll probably merge that and cut a release sometime tomorrow.

**Comment by brandonbloom** [comment]
This is now available in the 2021.09.07 release.
