### ISSUE TITLE
[FEATURE] package for popular package managers

### ISSUE THREAD

**Issue by brandonbloom** [deref/exo#301]
# Package Managers

Which package managers? Whatever is supported by https://goreleaser.com/

Priorities:

- [x] Mac homebrew formula in our private tap here: https://github.com/deref/homebrew-tap
- [x] Linux as .deb, .rpm and .apk

Also consider:

- [ ] Snapcraft for Ubuntu software store
- [ ] others?

**Comment by mausch** [comment]
Nix package: https://github.com/NixOS/nixpkgs/pull/137542

> How does licensing affect packaging?
As discussed in https://github.com/deref/exo/discussions/302 the nix package is marked as "unfree" meaning nix will build it locally from sources (downloading and/or building all necessary tools too) when installing, which takes several minutes.

**Comment by vincentjames501** [comment]
I'd love to use this with the homebrew package manager on MacOS, however, the licensing of this project makes it tricky as we can't choose an option from: https://spdx.org/licenses/ .  I know it has been discussed in #299, but is there any chance of choosing a different license? I think this is an excellent tool and I fear the custom license may provide a less optimal developer experience and thus hinder adoption (I recognize this is an opinion. I'll just say that the first thing I tried on my machine to install exo was `brew install exo` and when it didn't exist, I always end up questioning whether it is a "real" project and I know this one is!).

```ruby
class Exo < Formula
  desc "A process manager & log viewer for dev"
  homepage "https://exo.deref.io/"
  url "https://github.com/deref/exo/archive/refs/tags/v2021.09.14.tar.gz"
  sha256 "42b44c570f66d6d0e84e8723087d7b92986f945986e4d22b132c47ebb890afa2"
  license :public_domain

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w"), "./cmd/exo"
  end

  test do
    version = shell_output("#{bin}/exo version")
    assert_match /\d+\.\d+\.\d+/, version
    
    system "#{bin}/exo daemon"
    sleep 3
    assert_match "healthy:   true", shell_output("#{bin}/exo status")
  ensure
    system "#{bin}/exo exit"
  end
end
```

**Comment by brandonbloom** [comment]
Hi @vincentjames501, Thanks for reaching out.

As mentioned before, open to relicensing, but still TBD. We're working on a SaaS component now & need to figure out how to integrate it. The ideal would be fore Exo to be entirely "proper" Open Source core, but there is maintenance overhead that we need to sort out. Will update this thread when things evolve there.

Beyond the licensing concerns, exo is still very young and evolving rapidly. I'm a little bit concerned about having to open bump-version PRs against Homebrew with ~monthly frequency. Though, I'll admit that I am not super familiar with the process to know if this is actually an issue or not.

Would a private tap/repository satisfy your use case? My understanding is that we can create https://github.com/deref/homebrew-deref and that would would then work automatically if you did `brew install deref/deref/exo` - Additionally, this approach is more flexible on licenses and self-updating binaries.

What do you think?

**Comment by vincentjames501** [comment]
@brandonbloom , I think that would be a great solution for the time!

**Comment by brandonbloom** [comment]
OK, we'll look at that more closely soon. I updated the description of this issue to suggest that we use https://goreleaser.com/

Work in progress here:  https://github.com/deref/exo/pull/395

Have to do a little bit of a dance to to switchover from our existing release & self-upgrade machinery without losing any users along the way. There are other priorities now, so might take a couple of weeks for us to get this all the way pushed through. Thanks for your patience!

**Comment by brandonbloom** [comment]
@BenElgar What is our status here? Also, I think we can't call this complete until the docs are fully updated.

**Comment by BenElgar** [comment]
I improved the docs for install here: https://github.com/deref/exo-docs/pull/1

**Comment by brandonbloom** [comment]
Great, thanks!

@vincentjames501 et al, please let us know if you have any trouble with the packages.
