### ISSUE TITLE
[FEATURE] Delete Networks and Volumes from the GUI

### ISSUE THREAD

**Issue by jwmza** [deref/exo#310]
**Describe the solution you'd like**
I'd like to be able to delete Networks and Volumes from their tabs in the same way we can currently delete Processes and Containers from the main logs screen.

**Describe alternatives you've considered**
Alternatively, there could be one screen with a full list of all components with delete and edit options.

**Comment by brandonbloom** [comment]
The API for this should be the same, so you should be able to implement this no problem.
