### ISSUE TITLE
[BUG] Empty log lines not captured

### ISSUE THREAD

**Issue by BenElgar** [deref/exo#326]
**Describe the bug**
Logs that consist of nothing other than a new line character are not captured.

**To Reproduce**
Run either the docker compose or Procfile below:
```yaml
services:
  t0:
    image: bash
    command: sh -c 'i=0; while true; do echo; sleep 1; done'
```
```
t0: sh -c 'i=0; while true; do echo; sleep 1; done'
```

Neither will emit any logs and the Procfile will cause the following error in the server:
```
13:14:58    server 2021/09/13 13:14:58 interpreting syslog message: expected MSG
```

**Expected behavior**
Exo should log lots of empty log lines.

**Additional context**
My understanding is that it is a violation of the procotol to send empty messages so, by removing new line characters, we are creating invalid syslog packets.
> There is no minimum length of the syslog message although sending a syslog packet with no contents is worthless and SHOULD NOT be transmitted.

https://datatracker.ietf.org/doc/html/rfc3164#section-4.1

**Comment by brandonbloom** [comment]
> My understanding is that it is a violation of the procotol to send empty messages

That understanding doesn't seem to jive with the quoted text you included:

> > There is no minimum length of the syslog message

This seems to imply to me that an empty string message is valid. However...

> a syslog packet with no contents is worthless and SHOULD NOT be transmitted

This says an empty _packet_. That is no message, and no other metadata in the packet.

I can't find any evidence in the spec or easily searchable on line about whether or not newlines are expected to be included, but I would assume not based on the fact that empty messages are valid.

Looking at the implementation of the underlying syslog library, I think that the bug we have here is that they explicitly convert empty strings to nil when processing messages and I assumed nil meant that there was no message field in the packet. They can't differentiate no message field vs empty message in the parsed results, so I just assume no message field is an empty message.

The idea that empty packets are useless assumes that the syslog isn't really intended for arbitrary lines of output, it's intended for log messages! Blank log messages are indeed useless, but we want to do our best to preserve the illusion that the output is  stdout plain text, not arbitrary log events.
