### ISSUE TITLE
[BUG] logs command loses characters after process prints to stderr

### ISSUE THREAD

**Issue by ryfow** [deref/exo#327]
**Describe the bug**

Once a process prints to stderr, `exo logs` stops showing the first character of log lines and the timestamp printing ends.

**To Reproduce**

1. Create a process that logs to stderr.
2. See that the first character of output is missing
 
```
~/s/dev-environment ❯❯❯ echo '#!/usr/bin/env bash\n echo "stderr" 1>&2\n echo "stdout"' > stderr-printer
~/s/dev-environment ❯❯❯ chmod +x stderr-printer
~/s/dev-environment ❯❯❯ exo new process stderr-printer ./stderr-printer
mg2wm9hgy7148hjr5y9eabv8rg
~/s/dev-environment ❯❯❯ exo logs stderr-printer
08:43:21 stdout
tderr
C
```

**Expected behavior**
I expect `exo logs` to print the first character of log lines.

**System Info (please complete the following information):**
 - OS: macOS
 - Component cli
 - Version 2021.09.09

**Comment by BenElgar** [comment]
Thank you for the report! I can confirm that I can reproduce and that it appears to be to do with the terminal escape sequence used here: https://github.com/deref/exo/blob/supervise-logging/cmd/exo/logs.go#L117

Working on a fix.

**Comment by BenElgar** [comment]
@ryfow we've merged a fix and we've released a new version. Do you reckon you could try this again?

**Comment by ryfow** [comment]
Yep, looks good!

**Comment by BenElgar** [comment]
Marvellous! Let us know if you encounter any other issues! :)
