### ISSUE TITLE
[BUG] `.exo` directory growing very large in size

### ISSUE THREAD

**Issue by jwmza** [deref/exo#336]
**Describe the bug**
My production `.exo/var` directory has inflated to >2 GB in size, ~99% of which is in `logs` 

**Expected behavior**
Some sort of reasonable garbage collection to keep the storage used small. Ideally it would be nice to have a user configurable storage limit so that users could decide whether they want unlimited history, or any byte amount.

**Screenshots**
```
~/.exo/var/logs $ ls -l -h -a
total 424K
drwx------ 2 jwmza jwmza 4.0K Sep 15 13:06 .
drwx------ 4 jwmza jwmza 4.0K Sep 17 18:28 ..
-rw-r--r-- 1 jwmza jwmza 303K Sep 14 12:03 000012.sst
-rw-r--r-- 1 jwmza jwmza 7.2K Sep 14 15:59 000013.sst
-rw-r--r-- 1 jwmza jwmza 2.6K Sep 15 13:06 000014.sst
-rw-r--r-- 1 jwmza jwmza   20 Sep 15 13:06 000018.vlog
-rw-r--r-- 1 jwmza jwmza 2.0G Sep 15 13:06 000019.vlog      << This one seems to be the problem
-rw-r--r-- 1 jwmza jwmza 128M Sep 17 18:28 00013.mem
-rw-r--r-- 1 jwmza jwmza 1.0M Aug 19 12:55 DISCARD
-rw------- 1 jwmza jwmza   28 Aug 19 12:55 KEYREGISTRY
-rw-r--r-- 1 jwmza jwmza    4 Sep 15 13:06 LOCK
-rw------- 1 jwmza jwmza  282 Sep 15 13:06 MANIFEST
```

**Comment by brandonbloom** [comment]
I thought we had this garbage collection, but maybe we forgot to enable it or it broke. Will investigate. Thanks!

**Comment by BenElgar** [comment]
So there is definitely something that looks like garbage collection built in: https://github.com/deref/exo/blob/main/internal/logd/logd.go#L67-L70

It would appear that the issue is that `NextLog` isn't appropriately returning a log when the `after` parameter provided is `nil`.
https://github.com/deref/exo/blob/131642a2bfaae9255251042f77529e227caf243f/internal/logd/store/badger/store.go#L52
If you pass in a nil value the function returns a nil log and a nil error.

**Comment by brandonbloom** [comment]
@BenElgar Thanks for investigating. If you feel like you know how to fix it, please self-assign. Otherwise, lmk and I can take a look at it.

**Comment by jwmza** [comment]
At risk or being repetitive, even if there is a garbage collector I think it's a good idea to allow user configurable storage limits in a way such that we can intelligently keep anywhere from very little history to arbitrarily large history based on what the user wants and their machine. Sensible default value ofc.

**Comment by brandonbloom** [comment]
Let's fix the bug first and then consider any configuration as a follow-up feature request.

**Comment by BenElgar** [comment]
I spent a little time on it and couldn't immediately figure out how to construct a valid `nextName` in that function for the first entry in the store — `mustLogFromKey` would panic unexpectedly. That being said, I'm sure I can figure it out.

**Comment by brandonbloom** [comment]
@BenElgar Don't worry about it. I'm going to replace the logging backend with sqlite very soon anyway. I'll fix this in the process (and surely break something else).
