### ISSUE TITLE
Pick a better port for syslog server

### ISSUE THREAD

**Issue by brandonbloom** [deref/exo#38]
We probably should make this configurable. It looks like 4500 is commonly used for IPSec NAT traversal, so this might break some VPNs.

_Originally posted by @kendru in https://github.com/deref/exo/pull/23#r677047390_

**Comment by brandonbloom** [comment]
assigning to @kendru to address as part of the configuration changes he's making in support of dogfooding.

**Comment by kendru** [comment]
This is now configurable per #76
