### ISSUE TITLE
Create better global `Modal` system

### ISSUE THREAD

**Issue by jwmza** [deref/exo#386]
Gonna merge this as-is and loop around when or before we need more modals in order to set up a global store-based modal system. There's a good example implementation here: https://svelte.dev/repl/033e824fad0a4e34907666e7196caec4?version=3.43.1

_Originally posted by @jwmza in https://github.com/deref/exo/pull/378#issuecomment-931517619_

**Comment by brandonbloom** [comment]
I spotted another `alert` somewhere. We should really fix this before they get out-of-hand.

**Comment by jwmza** [comment]
@brandonbloom fixing this in #535 now. I'll set it up so it's easy to use this instead of `alert` in future.
