### ISSUE TITLE
NextLog scan is broken

### ISSUE THREAD

**Issue by brandonbloom** [deref/exo#40]
Is this correct? If I'm reading this right, we are looking for a log with the same name as the key, but the key is `(log + <255>, id).

_Originally posted by @kendru in https://github.com/deref/exo/pull/23#r677096718_

**Comment by brandonbloom** [comment]
@kendru Do you want to take on fixing this either (A) directly or (B) as part of the secondary index work? You're definitely better at this bit fiddling and index scanning than me.

Alternatively, we can do sqlite, which might be more appropriate for this subsystem :-P

**Comment by kendru** [comment]
@brandonbloom I'll fix this. I'll just do the same bit fiddling that we're doing elsewhere, but the larger storage change that I'm working will make this a non-issue.
