### ISSUE TITLE
[BUG] Stopping Next.js dev process spins indefinitely

### ISSUE THREAD

**Issue by jwmza** [deref/exo#424]
**Describe the bug**
Stopping Next.js dev process spins indefinitely. After pressing the "stop" button in the GUI, the process stops, but is in a seemingly infinite spinning state unable to be re-started until the web page is refreshed.

**To Reproduce**
1. Start a Next.js process (in this case the exo landing page)
2. Stop the process from the GUI

**Expected behavior**
Quickly stop the process and return to a non-spinning, runnable state.

**Screenshots**
After pressing the "stop" button in the GUI, the process stops, but is in a seemingly infinite spinning state unable to be re-started until the web page is refreshed:
![image](https://user-images.githubusercontent.com/51100181/137769589-0815fdcc-0517-48c0-83b4-0d547dca690f.png)
![image](https://user-images.githubusercontent.com/51100181/137770024-46acad70-88bb-4d2d-bcd0-e969c9ef8bba.png)
After refresh:
![image](https://user-images.githubusercontent.com/51100181/137769692-af988d96-35c6-4fab-a07b-f84690bf5fdb.png)

**Comment by brandonbloom** [comment]
Does `exo stop gui` work as expected? Or does that cause it to spin indefinitely as well?

**Comment by brandonbloom** [comment]
@jwmza more info needed please :)

**Comment by BenElgar** [comment]
Confirm that I can recreate. Investigating.
