### ISSUE TITLE
Handle stopping logio and supervised processes

### ISSUE THREAD

**Issue by kendru** [deref/exo#44]
When we stop a process, we send SIGKILL to the logio process, orphaning the supervised process (and not stopping it). Instead, we should send a `SIGTERM` to logio, indicating that it should gracefully stop its child process, wait for termination, then stop itself. Configurable timeouts should be used in both exo and the supervisor, after which the child process should be killed. @BenElgar let me know if you have questions.

**Comment by brandonbloom** [comment]
> When we stop a process, we send SIGKILL to the logio process

Seems like this changed now?
https://github.com/deref/exo/pull/43

> orphaning the supervised process (and not stopping it)

Was that true? I thought they were part of a process group and should have died together. Is that not true?

> we should signal logio that it should gracefully stop its child process, wait for termination, then stop itself. Configurable timeouts should be used in both exo and the supervisor, after which the child process should be killed.

The hard requirement is a proper kill. Graceful shutdown with only OK if we include the timeout mechanism.

**Comment by kendru** [comment]
No, sending SIGKILL will terminate the supervisor process, but it will orphan the children. The process never even receives the SIGKILL signal - it is entirely handled in the OS. Ben ran into this right away with the node process because clicking "stop" just killed the supervisor, but the node server was still running, and he could not restart it.

**Comment by kendru** [comment]
The change that Ben made is a stopgap that will usually terminate the supervisor and the child process, but if the child is not well-behaved, it can still hang around. We need the supervisor to handle SIGTERM and SIGINT by trying to stop the child process (and forcefully killing it if it does not stop gracefully) then exiting itself. The `stop` handler for a process type should probably also wait on a slightly longer timeout after trying to stop the supervisor before killing it.

**Comment by brandonbloom** [comment]
fixed on main branch
