### ISSUE TITLE
[BUG] exo env is broken

### ISSUE THREAD

**Issue by finnigantime** [deref/exo#460]
**Describe the bug**
`exo env` is giving me an error

**To Reproduce**
1. `exo env`

**Expected behavior**
Works! Prints my env vars.

**Screenshots**
```
➜  rainbow git:(finnigan/load-nonretryable) ✗ exo env
Error: unmarshalling output: json: cannot unmarshal string into Go struct field DescribeEnvironmentOutput.variables of type api.VariableDescription
unmarshalling output: json: cannot unmarshal string into Go struct field DescribeEnvironmentOutput.variables of type api.VariableDescription
➜  rainbow git:(finnigan/load-nonretryable) ✗ exo version
2021.10.28-2
```

**System Info (please complete the following information):**
 - OS: macOS
 - Component cli
 - Version 2021.10.28-2

**Comment by brandonbloom** [comment]
Hey @finnigantime, thanks for the report. I suspect that this is the same underlying issue as you had earlier with the server failing to restart on upgrade. Can you confirm if this is still broken for you?

**Comment by finnigantime** [comment]
Fixed now!
