### ISSUE TITLE
[UX] submit button below directory picker with long file list is confusing

### ISSUE THREAD

**Issue by brandonbloom** [deref/exo#507]
See image:

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/119164/141864999-d217a386-89aa-445a-8502-5f916ce2890e.png">

I didn't realize I had to scroll down at first. Would be nice if the directory list was a scrollable region with a max-height, since I didn't care about any entries in the list, I just wanted to click create where I was at.

**Comment by jwmza** [comment]
Thanks for noting this. I agree - will fix this.

**Comment by brandonbloom** [comment]
Fixed by #523
