### ISSUE TITLE
Implement `exo feedback` command

### ISSUE THREAD

**Issue by kendru** [deref/exo#64]
1. Create command: `exo feedback`
2. This command should open the default editor with a temporary file.
3. When this file is saved, a message is sent to Deref with the feedback.

**Comment by brandonbloom** [comment]
Do we really need this? We have various feedback mechanisms via Github, Slack, etc. I'm not sure why terminal feedback is worthwhile, vs just exposing like an email address or something.

**Comment by kendru** [comment]
I don't think it's necessary. It's just an idea that I had for a low-friction feedback mechanism that I wanted to write down instead of forgetting immediately.
