### ISSUE TITLE
Misleading UI in the readme

### ISSUE THREAD

**Issue by norman784** [deref/exo#65]
The advertised UI in the readme is not the same as the web app.

**Comment by brandonbloom** [comment]
You're right, it's a mockup we created, but we neglected to put an up-to-date screenshot in there. Assigning to @jwmza who can update it with a latest high-fi design soon.

**Comment by brandonbloom** [comment]
The UI has been considerably overhauled (and continues to be). Leaving this open to track updating the website along with the next release.

**Comment by jwmza** [comment]
Yeah, the new GUI is much different than both the README/Web mockup and the old GUI. Will sync up the public snapshots once the new release is locked in.

**Comment by brandonbloom** [comment]
OK @jwmza, latest release just went out! Could you please update the website and readme with an up-to-date screenshot now? Thanks :)

**Comment by jwmza** [comment]
Done @brandonbloom

**Comment by jwmza** [comment]
Will follow up with bringing back light/dark variants on the website and using an optimized SVG mockup with 99-100% accuracy once that is ready for release, which should be soon considering the CSS variable groundwork is ready to go.
