### ISSUE TITLE
PORT environment variable should not be set by default

### ISSUE THREAD

**Issue by kendru** [deref/exo#81]
When starting a new process imported from a Procfile, exo automatically injects a `PORT` environment variable into the new process. This can have unintended consequences. For example, my application relies on a config file to specify the port, but it allows PORT to override this value. I expect that if I do not set this environment variable in a `Procfile`, `.envrc`, or similar that it will not be set magically.

**Comment by kendru** [comment]
@brandonbloom why are we setting PORT in `import/procfile/convert.go`?

**Comment by brandonbloom** [comment]
This is just how Procfiles are expected to work. See "Port Assignment" here: http://blog.daviddollar.org/2011/05/06/introducing-foreman.html

If you don't want that behavior, you need to either (A) change the application or (B) avoid Procfiles & use our own manifest format.
